name: Publish Dev Version
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**.md'

jobs:
  publish-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Generate unique dev version
        id: version
        run: |
          RANDOM_SUFFIX=$(python -c "import random; import string; print(''.join(random.choice(string.ascii_lowercase) for _ in range(6)))")
          VERSION="0.0.0.dev0+${RANDOM_SUFFIX}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          sed -i "s/version = .*/version = \"${VERSION}\"/" pyproject.toml
          echo "Generated version: ${VERSION}"

      - name: Build package
        run: python -m build

      - name: Verify package
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          rm -rf dist/
          python -m build
          twine upload --skip-existing dist/*