name: Publish Release Version

on:
  release:
    types: [ created ]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          VERSION=${VERSION#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          sed -i "s/version = .*/version = \"${VERSION}\"/" pyproject.toml
          echo "Using release version: ${VERSION}"

      - name: Build package
        run: python -m build

      - name: Verify package
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*